#!/usr/bin/env python3
import os
import sys
import stat
import setup

sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))
from charmhelpers.core import (
    hookenv,
    host,
)


hookenv.log('Database Relation joined', 'INFO')
