#!/usr/bin/env python3
# coding=utf-8

import os
import sys

import stat
import setup
from subprocess import check_call
#setup.pre_install()

#sys.path.insert(0, os.environ['CHARM_DIR'])
#import lib.charmhelpers.core.hookenv
sys.path.insert(0, os.path.join(os.environ['CHARM_DIR'], 'lib'))

#os.system('kamdbctl drop')


def delete():
  run_command = ['docker', 'exec','kamailio', 'kamdbctl', 'drop' ]
  check_call(run_command)
  hookenv.log('Kamailio relation deleted', 'INFO')


if __name__ == "__main__":
  delete()
